import type { Metadata } from "next";
import "./styles/styles.scss";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";

export const metadata: Metadata = {
  title: "OZ Green Star Landscaping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="ozgs">
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
